from homeassistant.const import CONF_ENTITY_ID, CONF_HOST, CONF_NAME, CONF_PORT

DOMAIN = "artnet_receiver"
DEFAULT_NAME = "ArtNet Receiver"
DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 6454
DEFAULT_UNIVERSE = 0
SUPPORTED_ENTITY_DOMAINS = ("light", "switch")

CONF_UNIVERSE = "universe"
CONF_POLLING_MODE = "polling_mode"
CONF_MAPPINGS = "mappings"
CONF_PROFILE = "profile"
CONF_CHANNEL = "channel"
CONF_RED_CHANNEL = "red_channel"
CONF_GREEN_CHANNEL = "green_channel"
CONF_BLUE_CHANNEL = "blue_channel"
CONF_WHITE_CHANNEL = "white_channel"
CONF_WARM_WHITE_CHANNEL = "warm_white_channel"
CONF_COLD_WHITE_CHANNEL = "cold_white_channel"
CONF_COLOR_TEMP_CHANNEL = "color_temp_channel"
CONF_ADD_ANOTHER = "add_another"
CONF_ENTRY_ID = "entry_id"
CONF_VALUE = "value"
CONF_RED = "red"
CONF_GREEN = "green"
CONF_BLUE = "blue"
CONF_WHITE = "white"
CONF_WARM_WHITE = "warm_white"
CONF_COLD_WHITE = "cold_white"
CONF_COLOR_TEMP = "color_temp"
CONF_MAPPING_ENTITY = "mapping_entity"

PROFILE_SWITCH = "switch"
PROFILE_DIMMER = "dimmer"
PROFILE_RGB = "rgb"
PROFILE_RGBW = "rgbw"
PROFILE_RGBWW = "rgbww"
PROFILE_COLOR_TEMP = "color_temp"

POLLING_MODE_FAST = "fast"
POLLING_MODE_NORMAL = "normal"
POLLING_MODE_LOW = "low"
DEFAULT_POLLING_MODE = POLLING_MODE_NORMAL
POLLING_MODE_TO_INTERVAL_MS = {
    POLLING_MODE_FAST: 50,
    POLLING_MODE_NORMAL: 100,
    POLLING_MODE_LOW: 200,
}

ARTNET_HEADER = b"Art-Net\x00"
ARTNET_OPCODE_DMX = 0x5000
DMX_SWITCH_ON_THRESHOLD = 126
DMX_CHANNEL_MIN = 1
DMX_CHANNEL_MAX = 512
ARTNET_UNIVERSE_MIN = 0
ARTNET_UNIVERSE_MAX = 32767
DIAGNOSTIC_EVENT_INTERVAL_SECONDS = 1

SERVICE_TEST_CHANNEL = "test_channel"
SERVICE_TEST_MAPPING = "test_mapping"

PLATFORMS = ("sensor",)

BASE_CONFIG_KEYS = (CONF_NAME, CONF_HOST, CONF_PORT, CONF_UNIVERSE, CONF_POLLING_MODE)
ENTITY_CONFIG_KEYS = (
    CONF_ENTITY_ID,
    CONF_PROFILE,
    CONF_CHANNEL,
    CONF_RED_CHANNEL,
    CONF_GREEN_CHANNEL,
    CONF_BLUE_CHANNEL,
    CONF_WHITE_CHANNEL,
    CONF_WARM_WHITE_CHANNEL,
    CONF_COLD_WHITE_CHANNEL,
    CONF_COLOR_TEMP_CHANNEL,
)
